import { useState } from "react"
import supabase from "./supabase"
import logo from "./assets/BME-Logo.png"
import "./App.css"


const SALESMEN = [
  "Nabin",
  "Shaji",
  "Arshad",
  "Shabeeb",
  "Imtiaz",
]

// Each key is a brand, each value is an array of SKUs under that brand
const PRODUCTS = {
  "Mega": [
    "MEGA SARDINES IN TOMATO SAUCE [100x155G]",
    "MEGA SARDINES IN TOMATO SAUCE CHILI ADDED [100x155G]",
    "MEGA SARDINES IN TOMATO SAUCE EXTRA HOT [100x155G]",
    "MEGA SARDINES IN NATURAL OIL [100x155G]",
    "MEGA SARDINES IN TOMATO SAUCE [24x425G]",
    "MEGA SARDINES IN TOMATO SAUCE CHILI ADDED [24x425G]",
    "MEGA SARDINES SPANISH STYLE [100x155G]",
    "MEGA SARDINES FRIED W/ TAUSI [100x155G]",
    "MEGA SARDINES FRIED IN HOT AND SPICY [100x155G]",
    "MEGA MACKEREL IN TOMATO SAUCE [50X155G]",
    "MEGA MACKEREL IN TOMATO SAUCE CHILI ADDED [50x155G]",
    "MEGA MACKEREL IN NATURAL OIL [50X155G]",
    "MEGA MACKEREL IN NATURAL OIL [24X425G]",
    "MEGA SQUID IN SOY SAUCE [50X155G]",
    "MEGA SQUID IN SOY SAUCE WITH CHILI ADDED [50X155G]",
    "MEGA PRIME NATA DE COCO WHITE [24x425G]",
    "MEGA PRIME NATA DE COCO LYCHEE [24x425G]",
    "MEGA PRIME PIECES & STEMS MUSHROOMS [48x198G]",
    "MEGA PRIME PIECES & STEMS MUSHROOMS [24x425G]",
    "MEGA PRIME WHOLE MUSHROOMS [48x198G]",
    "MEGA PRIME WHOLE MUSHROOMS [24x425G]",
    "MEGA PRIME WHOLE KERNEL CORN [24x185G]",
    "MEGA PRIME WHOLE KERNEL CORN [24x425G]"
  ],
  "Monde": [
    "MONDE BUTTER COCONUT 510001 [24X(12X14G)]",
    "MONDE BREADSTIX 510003 [30X130G]",
    "MONDE EGGNOG COOKIES 510010 [20X130G]"
  ],
  "LuckyMe": [
    "LUCKY ME! PANCIT CANTON HOT CHILI 400073 [12X(6X60G)]",
    "LUCKY ME! PANCIT CANTON KALAMANSI 400083 [12X(6X60G)]",
    "LUCKY ME! PANCIT CANTON CHILIMANSI 400093 [12X(6X60G)]",
    "LUCKY ME! PANCIT CANTON ORIGINAL 400103 [12X(6X60G)]",
    "LUCKY ME! PANCIT CANTON SWEET & SPICY 400112 [12X(6X60G)]",
    "LUCKY ME! INSTANT MAMI BEEF 400053 [12X(6X55G)]",
    "LUCKY ME! INSTANT MAMI CHICKEN 400063 [12X(6X55G)]",
    "LUCKY ME! LOMI CHICKEN & SEAFOOD 400553 [12X(6X65G)]",
    "LUCKY ME! SUPREME CUPS BULALO 510061 [30X70G]",
    "LUCKY ME! SUPREME CUPS LAPAZ BATCHOY 510071 [30X70G]",
    "LUCKY ME! SUPREME CUPS CHICKEN MAMI 510065 [30X70G]",
    "LUCKY ME! SUPREME CUPS JJAMPONG 510068 [30X70G]",
    "LUCKY ME! SUPREME CUPS SEAFOOD 510074 [30X70G]",
    "LUCKY ME! SUPREME CUPS BEEF MAMI 510057 [30X70G]",
    "LUCKY ME! MINI CUPS BULALO 510016 [48X40G]",
    "LUCKY ME! MINI CUPS LAPAZ BATCHOY 510021 [48X40G]",
    "LUCKY ME! MINI CUPS CHICKEN 510018 [48X40G]",
    "LUCKY ME! MINI CUPS BEEF 510014 [48X40G]",
    "LUCKY ME! MINI CUPS JJAMPONG 510019 [48X40G]",
    "LUCKY ME MINI SOTANGHON 28G"
  ],
  "Dahabi": [
    "DAHABI CHAKKI ATTA 10 X 2KG",
    "DAHABI CHAKKI ATTA 4 X 5KG",
    "DAHABI OMANI BUR FLOUR 10 X 2KG",
    "DAHABI OMANI BUR FLOUR 4 X 5KG",
    "DAHABI BUR FLOUR 10 X 2KG",
    "DAHABI GOLDEN GRAIN FLOUR 10 X 2KG",
    "DAHABI PATENT FLOUR [10x1KG]",
    "DAHABI ALL PURPOSE FLOUR [3x5KG]",
    "DAHABI WHITE FLOUR NO.1 [1x10KG]",
    "DAHABI FLOUR ATTA [3x5KG]",
    "DAHABI FLOUR NO.2 ATTA [1x10KG]"
  ],
  "Sweet Factory": [
    "SWFY MINI COLA BOTTLES 40G SFR-0002 [6x36]",
    "SWFY TEDDY BEARS 40G SFR-0003 [6x36]",
    "SWFY FIZZY COLA BOTTLES 40G SFR-0001 [6x36]",
    "SWFY TINY HEARTS 40G SFR-0020 [6x36]",
    "SWFY SUGARY BALLS 40G SFR-0021 [6x36]",
    "SWFY MINI COLA BOTTLES 80G SFR-0005 [6x24]",
    "SWFY TEDDY BEARS 80G SFR-0006 [6x24]",
    "SWFY FIZZY COLA BOTTLES 80G SFR-0004 [6x24]",
    "SWFY WILD BERRIES 80G SFR-0007 [6x24]",
    "SWFY MINI COLA BOTTLES 160G SFR-0010 [6x12]",
    "SWFY TEDDY BEARS 160G SFR-0013 [6x12]",
    "SWFY FIZZY COLA BOTTLES 160G SFR-0008 [6x12]",
    "SWFY WIGGLY SNAKES 160G SFR-0014 [6x12]",
    "SWFY WILD BERRIES 160G SFR-0015 [6x12]",
    "SWFY PEACH RINGS 160G SFR-0011 [6x12]",
    "SWFY SOUR SPACE MIX 160G ( SOUR/FIZZY/SUGARED) SFR-0022 [6x12]",
    "SWFY COSMIC MIX 160G ( OILY) SFR-0023 [6x12]",
    "SWFY ROUND LOLLIPOP 40G SFL-0001 [4x25]",
    "SWFY SPIRAL LOLLIPOP 40G SFL-0002 [4x25]",
    "SWFY ROUND LOLLIPOP 20G SFL-0037 [4x30]",
    "SWFY SPIRAL LOLLIPOP 20G SFL-0040 [4x30]",
    "SWFY DINOSAUR CHOMP 5G SFC-0001 [12x12]",
    "SWFY BOXING STAR 5G SFC-0002 [12x12]",
    "SWFY TOOTH GRAB 5G SFC-0003 [12x12]",
    "SWFY CANDY DISPENSER 30G SFC-0004 [12x12]",
    "SWFY DINOSAUR WATERGUN CANDY TUBES 10G SFC-0005 [6x12]",
    "SWFY SHARK GRABS CANDY TOYS 10G SFC-0006 [6x12]",
    "SWFY MANUAL FAN CANDY TOYS 5G SFC-0007 [12x12]",
    "SWFY DINOSAUR PROJECTOR CAMERA CANDY TOYS 10G SFC-0008 [6x12]",
    "SWFY CAMERA CANDY TOYS FOR GIRL 10G SFC-0009 [6x12]",
    "SWFY COLOURFUL SURPRISE EGG 10G SFC-0010 [12x12]",
    "SWFY BIG BUBBLE GUM ROLL 40G SFC-0011 [12x12]"
  ],
  "KDD": [
    "KDD THICK QISHTA CREAM 125ML [40X125ML]",
    "KDD THICK CREAM QISHTA 250ML [4X6X250ML]",
    "KDD TOMATO PASTE 135 GM [5X8X135 GM]",
    "KDD BECHAMEL SAUCE 1LTR [12X1LTR]",
    "KDD BECHAMEL SAUCE 500ML [12X500ML]",
    "KDD CHOCOLATE MILK 125ML [18X125ML]",
    "KDD CHOCOLATE MILK 180ML [3X6X180 ML]",
    "KDD BANANA MILK 125ML [18X125ML]",
    "KDD BANANA MILK 180ML [3X6X180 ML]",
    "KDD STRAWBERRY MILK 125ML [18X125ML]",
    "KDD STRAWBERRY MILK 180ML [3X6X180 ML]",
    "KDD COCKTAIL NECTAR 125ML [18X125ML]",
    "KDD COCKTAIL NECTAR 180ML [24X180ML]",
    "KDD MANGO NECTAR 125ML [18X125ML]",
    "KDD MANGO NECTAR 180ML [24X180ML]",
    "KDD GUAVA NECTAR 180ML [24X180ML]",
    "KDD APPLE JUICE 180ML [24X180ML]",
    "KDD ORANGE JUICE 180ML [24X180ML]",
    "KDD MILK COFFEE DRINK 250ML [18X250ML]",
    "KDD MILK COFFEE DOUBLESHOT ESPRESS 250ML [18x250ML]",
    "KDD MILK COFFEE ICED MOCHA 250ML [18X250ML]",
    "KDD CREAM DAIRY COOKING 1LTR [12X1LTR]",
    "KDD CREAM DAIRY COOKING 250ML [18X250ML]"
  ],
  "Voiz": [
    "VOIZ CRACKER SANDWICH CHOCOLATE 400627 [12x(10x28G)]",
    "VOIZ CRACKER SANDWICH STRAWBERRY 400628 [12x(10x28G)]",
    "VOIZ CRACKER SANDWICH CREAMY BUTTER 400624 [12x(10x28G)]",
    "VOIZ CRACKER SANDWICH MILK 400626 [12x(10x28G)]",
    "VOIZ CRISPY SANDWICH STRAWBERRY 23GX12 (276G)",
    "VOIZ CRISPY SANDWICH CRUNCH CHOCO CRISPIES 23GX12 (276G)",
    "VOIZ CRISPY SANDWICH COOKIES & CREAM 23GX12 (276G)",
    "VOIZ MINI WAFFLE CREAMY BUTTER 8GX24 (192G)",
    "VOIZ MINI WAFFLE STRAWBERRY 8GX24 (192G)",
    "VOIZ MINI WAFFLE CRUNCH CHOCO CRISPIES 8GX24 (192G)",
    "VOIZ MINI WAFFLE CHOCO MOCHA 8GX24 (192G)",
    "VOIZ MINI WAFFLE COOKIES & CREAM 8GX24 (192G)",
    "VOIZ MINI WAFFLE STRAWBERRY 8GX5 (40G)",
    "VOIZ MINI WAFFLE CRUNCH CHOCO CRISPIES 8GX5 (40G)",
    "VOIZ MINI WAFFLE COOKIES & CREAM 8GX5 (40G)",
    "VOIZ BITS MINI COOKIES VANILLA CREAM 20GX10 (200G)",
    "VOIZ BITS MINI COOKIES CHOCO CREAM 20GX10 (200G)"
  ],
  "Vicenzi": [
    "Vicenzi Long Finger",
    "Vicenzi Long Finger",
    "Vicenzi Brkfast 300gm",
    "VICENZI MV ASSORT PASTICCINI (10x250g)",
    "Vicenzi Cantuccini In Bag",
    "Vicenzi M/Snack H/N Cream",
    "Vicenzi M/Snack Pastry Cream",
    "Vicenzi Mv Asst.Pastry Tin",
    "VICENZI BOCCONCINI MILK CREAM 5231 [10x100gm]",
    "VICENZI M/FOGL PUFF PASTRY 125g+50g FREE",
    "VICENZI PUFF PASTRY LACTOSE FREE",
    "VICENZI M/FOGL CLASSICHE PUFF PASTRY 3228 (New Pack)",
    "VICENZI GLASATINE PUFF PASTRY 3229 (New Pack)",
    "VICENZI M/FOGL SNACK PASTRY CREAM 3273 (New Pack)",
    "VICENZI M/FOGL SNACK HAZELNUT CREAM 3274 (New Pack)",
    "VICENZI VICENZOVO STRAWBERRY 12X200G",
    "VICENZI M/FOGL PUFF PASTRY BITE-SIZE RASPBERY [10X90G]",
    "VICENZI M/FOGL PUFF PASTRY BITE-SIZE APRICOT & VANILLA [10X90G]"
  ],
  "Dutch Delight": [
    "DD WAFFLES SINGLES 39GM [4X36X39GM]",
    "DD WAFFLES DUOS 78GM [4X18X78GM]",
    "DD WAFFLES CARAMEL CUBE [8x230gm]",
    "DD WAFFLES MINIS 200GM [12X200GM]"
  ],
  "Grisbi": [
    "GRISBI CHOCOLATE CREAM 4200 [12x135GM]",
    "GRISBI HAZELNUT CREAM 4201 [12x135GM]",
    "GRISBI LEMON CREAM 4202 [12x135GM]"
  ],
  "Kuchen Meister": [
    "KM MARBLE CAKE IN BOX 580 [12X400GM]",
    "KM FRUIT CAKE IN BOX 582 [12X400GM]",
    "KM CHOCOLATE CAKE IN BOX 578 [12X400GM]",
    "KM CHOC SPLITS CAKE(STRACCIATELLA) IN BOX581 [12X400GM]"
  ],
  "Dorset": [
    "DORSET SIMPLY FRUITY MUESLI",
    "DORSET SIMPLY DELICIOUS MUESLI",
    "DORSET SUPER HIGH FIBRE CEREAL",
    "DORSET SUPER CRANBERY CHERY&ALMOND",
    "DORSET REALLY NUTTY MUESLI",
    "DORSET FRUITS NUTS&SEEDS CEREALS",
    "DORSET BERRIES&CHERIES",
    "DORSET HONEY GRANOLA [5X500GM]",
    "DORSET SIMPLY OAT GRANOLA",
    "DORSET NUT GRANOLA",
    "DORSET CHOCOLATE CHERRY GRANOLA",
    "DORSET BERRY GRANOLA"
  ],
  "Coffee Planet": [
    "COFFEE PLANET ORGANIC WHOLE BEANS M ROAST[12x250GM]",
    "COFFEE PLANET ITALIAN WHOLE BEANS DARK ROAST [12x250GM]",
    "COFFEE PLANET FRENCH WHOLE BEANS M ROAST [12x250GM]",
    "COFFEE PLANET BREAKFAST WHOLE BEANS M ROAST [12x250GM]",
    "COFFEE PLANET ORGANIC GROUND M ROAST[12x250GM]",
    "COFFEE PLANET ITALIAN GROUND DARK ROAST [12x250GM]",
    "COFFEE PLANET FRENCH GROUND M ROAST [12x250GM]",
    "COFFEE PLANET BREAKFAST GROUND M ROAST[12x250GM]",
    "COFFEE PLANET ITALIAN WHOLE BEANS DARK ROAST [10x1KG]",
    "COFFEE PLANET FRENCH WHOLE BEANS M ROAST [10x1KG]",
    "COFFEE PLANET CAPSULES ESPRESSO [10x(10x5.6GM)]",
    "COFFEE PLANET CAPSULES RISTRETTO [10x(10x5.6GM)]",
    "COFFEE PLANET CAPSULES LUNGO [10x(10x5.6GM)]",
    "COFFEE PLANET CAPSULES DECAF [10x(10x5.6GM)]",
    "COFFEE PLANET CAPSULES SINGL ORIGN BRAZIL[10x(10x5.6GM)]",
    "COFFEE PLANET CLASSIC GOLD 100G [6x100GM]",
    "COFFEE PLANET CLASSIC GOLD 200G [6x200GM]",
    "COFFEE PLANET COLD BREW BLACK NITRO [12x200ML]",
    "COFFEE PLANET COLD BREW LATTE [12x250ML]",
    "COFFEE PLANET COLD BREW CARAMEL LATTE [12x250ML]"
  ],
  "Hills Bros": [
    "HILLS COFFEE REGULAR 11.3oz[6x11.3oz]",
    "HILLS COLUMBIAN [6x10.3oz]",
    "HILLS FAT FREE VANILA CAPPUCIN [6x14oz]",
    "HILLS FRENCH VANILLA CAPPUCCIN [6x16oz]",
    "HILLS ENGLISH TOFFEE CAPPUCCIN [6x16oz]",
    "HILLS WHT CHOC CRMEL CAPPUCCIN [6x16oz]",
    "HILLS DBL CHOC MOCA CAPPUCCINO [6x16oz]",
    "HILLS DECAFF F/V CAPPUCCIN16oz [6x16oz]",
    "HILLS ORGNL BLEND [6x11.3oz]",
    "HILLS PERFECT BLNC [06x10.3oz]"
  ],
  "Twinings": [
    "TWININGS EARL GREY MEAST F17494 [12X10X2G]",
    "TWININGS ENGLISH BREAKFAST MEAST F17495 [12X10X2G]",
    "TWININGS E BKFST XTR STRG MEAST F17496 [12X10X2.3G]",
    "TWININGS PURE GREEN TEA MEAST F17497 [12X10X2G]",
    "TWININGS GREEN TEA + MINT MEAST F17498 [12X10X1.5G]",
    "TWININGS GREEN +FOREST FRTS MEAST F17499 [12X10X1.5G]",
    "CAMOMILE HON + VAN MEAST 6X20X1.5G IFN",
    "CHERRY + CINNAMON MEAST 6X20X2G IFN",
    "GINGER + LIME MEAST 6X20X1.5G IFN",
    "LEMON + GINGER MEAST 6X20X1.5G IFN",
    "PURE CAMOMILE MEAST 6X20X1G IFN",
    "PURE PEPPERMINT MEAST 6X20X2G IFN",
    "STRAWBERRY + MANGO MEAST 6X20X2G IFN",
    "EARL GREY MEAST 12X25X2G IFN",
    "ENGLISH AFTERNOON MEAST 12X25X2G IFN",
    "ENGLISH BREAKFAST MEAST 12X25X2G IFN",
    "E BKFST XTR STRG MEAST 12X25X2.3G IFN",
    "GREEN + FOREST FRTS MEAST 12X25X1.5G IFN",
    "GREEN LEM + HON MEAST 12X25X1.6G IFN",
    "GREEN TEA + GINGR MEAST 12X25X1.6G IFN",
    "GREEN TEA + LEMON MEAST 12X25X1.6G IFN",
    "GREEN TEA + MINT MEAST 12X25X1.5G IFN",
    "JASMINE GREEN TEA MEAST 12X25X1.8G IFN",
    "MOROCCAN MINT MEAST 12X25X1.6G IFN",
    "PURE GREEN TEA MEAST 12X25X2G IFN",
    "E BKFST XTR STRG MEAST 10X50X2.3G IFN",
    "EARL GREY MEAST 6X50X2G IFN",
    "ENGLISH BREAKFAST MEAST 6X50X2G IFN",
    "GREEN TEA + MINT MEAST 6X50X1.5G IFN",
    "PURE GREEN TEA MEAST 6X50X2G IFN",
    "LEMON + GINGER MEAST 6X50X1.5G IFN",
    "EARL GREY MEAST 6X100G TIN",
    "E BKFST XTR STRG MEAST 4X100X2.3G IFN",
    "EARL GREY MEAST 4X100X2G IFN",
    "ENGLISH BREAKFAST MEAST 4X100X2G IFN",
    "GREEN TEA + MINT MEAST 4X100X1.5G IFN",
    "GREEN TEA + LEMON MEAST 4X100X1.6G IFN",
    "PURE GREEN MEAST 4X100X2G IFN",
    "EARL GREY MEAST 6X200G TIN",
    "ENGLISH BREAKFAST MEAST 6X200G TIN",
    "TWININGS GOLDLINE ENG BFAST EXTR STR TIN 200gm [6x200gm]",
    "GUNPOWDER + MINT MEAST 6X200G TIN",
    "GUNPOWDER MEAST 6X200G TIN",
    "TWININGS GOLDLINE GRN GUN PDR TIN 500gm [6x500gm]",
    "TWININGS GOLDLINE EARL GREY TIN 500gm [6x500gm]",
    "TWINING ENG BF EXTRA STRONG MEAST TIN F17058 [6x500GM]",
    "TWININGS GREEN FOREST FRUITS TBAG F17500 [6x50]",
    "TWININGS GOLDLINE ENG BFAST TIN 500gm [6x500gm]",
    "TWININGS PURE ANISE MEAST 100018258 IFN [6X20X2.3GM]",
    "TWININGS PURE HIBISCUS MEAST 100018259 IFN [6X20X2.3GM]",
    "Twinings Pure Green Matcha Tea 25 Tea Bags, Herbal Tea"
  ],
  "Figaro Olives": [
    "FIGARO PLAIN GREEN 270gm [12x270gm]",
    "FIGARO PLAIN BLACK 270gm [12x270gm]",
    "FIGARO SLICED BLK OLIVE [12x230gm]",
    "FIGARO SLICED GRN OLIVE [12x230gm]",
    "FIGARO SLICED GREEN OLIVE [6x480gm]",
    "FIGARO SLICED BLACK OLIVE [6x480gm]",
    "FIGARO SLICED GREEN [6x1.5kg]",
    "FIGARO SLICED BLACK [6x1.5kg]",
    "FIGARO PLAIN GREEN 200gm [12x200gm]",
    "FIGARO PLAIN GREEN 2500gm [4x2500gm]",
    "FIGARO PLAIN GREEN 575gm [6x575gm]",
    "FIGARO STUFFED GREEN 2500gm [4x2500gm]",
    "FIGARO STUFFED GREEN 575gm [6x575gm]",
    "FIGARO STUFFED GREEN 270gm [12x270gm]",
    "FIGARO STUFFED GREEN 200gm [12x200gm]",
    "FIGARO PITTED OLIVES GRN 454gm [6x454gm]",
    "FIGARO PITTED OLIVES GRN 212gm [12x212gm]",
    "FIGARO PITTED OLIVES BLK 454gm [6x454gm]",
    "FIGARO PITTED OLIVES BLK 212gm [12x212gm]"
  ],
  "Figaro Oil": [
    "FIGARO OLIVE OIL LIGHT [6x750ml]",
    "FIGARO XTRA VIRGIN OLIVE OIL [6x750ml]",
    "FIGARO OLIVE OIL TINS [4x5Ltr]",
    "FIGARO OLIVE OIL 24696 [6X500ML]",
    "FIGARO XTRA VIRGIN OLIVE OIL 24697 [6X500ML]",
    "Salgado Pomace Olive Oil Tin - 400ml",
    "Salgado Pomace Olive Oil Tin - 2L"
  ],
  "DCL / SAF": [
    "Active Dried Yeast",
    "Instant Yeast",
    "Instant Yeast Saf Active Dry Yeast Tin",
    "Saf Active Dry Yeast Pack",
    "Saf Active Dry Yeast Pack",
    "Saf Active Dry Yeast"
  ],
  "Dunar": [
    "DUNAR RICE-ELONGA",
    "DUNAR RICE-ELONGA",
    "DUNAR RICE-ELONGA",
    "DUNAR RICE-FESTIVA",
    "DUNAR RICE-FESTIVA",
    "DUNAR RICE-FESTIVA",
    "DUNAR RICE-FUSION",
    "DUNAR RICE-FUSION",
    "DUNAR RICE-LEGACY",
    "DUNAR RICE-NUTRITIA BROWN"
  ],
  "Delicio": [
    "DELICIO 1000 ISLAND DRESSING - 12 X 267 ML",
    "DELICIO CHILLI MAYONNAISE - 12 X 300 ML",
    "DELICIO FRENCH DRESSING - 12 x 532 ML",
    "DELICIO FRENCH DRESSING - 12 X 267 ML",
    "DELICIO GARLIC MAYONNAISE - 12 X 300 ML",
    "DELICIO LITE MAYONNAISE - 12 X 500 ML",
    "DELICIO MAYOCHUP - 12 X 300 ML",
    "DELICIO RANCH DRESSING - 12 x 532 ML",
    "DELICIO RANCH DRESSING - 12 X 267 ML",
    "DELICIO REAL MAYONNAISE - 12 X 300 ML",
    "DELICIO SPICY RANCH DRESSING 12 X 267 ML",
    "DELICIO TOMATO KETCHUP (PREMIUM) - 12 X 500 GM",
    "DELICIO CAESARS DRESSING - 12 X 267 ML",
    "DELICIO ITALIAN DRESSING - 12 X 267 ML"
  ],
  "VC Touch": [
    "VC TOUCH CRYSTAL GRINDER SPAIN 40GM [6x40 GM]",
    "VC TOUCH CRYSTAL GRINDER ITALIA 45GM [6x45 GM]",
    "VC TOUCH CRYSTAL GRINDER MOROCCO 40GM [6x40 GM]",
    "VC TOUCH CRYSTAL GRINDER PEPPER 45 GM [6x45 GM]",
    "VC TOUCH CRYSTAL GRINDER SALT & HERBS 78GM [6x78 GM]",
    "VC TOUCH CRYSTAL GRINDER INDIA 48GM [6x48 GM]",
    "VC TOUCH CRYSTAL GRINDER TEX MEX 38GM [6x38 GM]",
    "VC TOUCH GRINDER HIMALAYAN PINK SALT 105 GM [6x105 GM]",
    "VC SYREN SAFFRON FILAMENTS 0.5 GM [25x12x0.5 GM]",
    "VC SYREN SAFFRON FILAMENTS 1GM [20x12x1 GM]",
    "VC SYREN SAFFRON FILAMENTS 2GM [15x12x2 GM]",
    "VC SYREN SAFFRON FILAMENTS 4GM [12x12x4 GM]",
    "VC SYREN SAFFRON FILAMENTS 8GM [8x12x8 GM]"
  ],
  "Solen": [
    "SOLEN OZMO EGG FACES 3540 [6x24x20gm]",
    "SOLEN OZMO FUN 8796 [4x24x23gm]",
    "SOLEN OZMO HOPPO BISC CHOCO 5710 [4x12x40gm]",
    "SOLEN LUPPO DREAM BAR CHOCOLATE 5935 [12x150gm]",
    "SOLEN LUPPO DREAM BAR CARAMEL 5932 [12x150gm]",
    "SOLEN LUPPO CAKEBITE MARSHMALOW 1207[12x12x25gm]",
    "SOLEN AMADA MOOD MILK CHOCOLATE 5771 [6x24x25gm]",
    "SOLEN AMADA MOOD CARAMEL MACC 5834 [24x135gm]",
    "SOLEN AMADA MOOD MILK CHOCOLATE 5705 [24x135gm]",
    "SOLEN AMADA NEXT WAFER HAZELNUT 9143 [24x117gm]",
    "SOLEN AMADA STIX MILK CHOCO 4093 [6x16x25gm]",
    "SOLEN AMADA STARZ MILKY 1312/5464 [12x12x37.5gm]",
    "SOLEN OZMO CORNET HAZELNUT 9012 [4x24x25gm]",
    "SOLEN OZMO HOXI POXI 4011 [4x12x36gm]",
    "SOLEN AMADA STIX MILK CHOCOLATE 4004 [4x12x40gm]",
    "SOLEN AMADA STIX HAZELNUT 4003 [4x12x32gm]",
    "SOLEN AMADA STIX COCONUT 4002 [4x12x32gm]"
  ]
  
}

// Structure: SCHEDULE[salesmanName][weekName][dayName] = [list of stores]
// Each salesman has 4 weeks, each week has 7 days
const SCHEDULE = {
  Nabin: {
    "Week 1": {
    Monday: [
      "AL NAHDA GIFT CENTER",
      "NIGHT TO NIGHT DEPARTMENT STORE LLC BR",
      "SAMA AL KHALEEJ TR",
      "FIRST DISCOUNTS CENTER",
      "ASWAQ AL SEYOUH GIFTS",
      "BLUE MART FRESH MINI MART LLC SHJ BR 3",
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ.BR-BRANCH 3",
      "KANZ AL BAHAR SUPERMARKET L.L.C"
    ],
    Tuesday: [
      "BURMA SM",
      "METRO MANILA SUPERMARKET BRANCH 1",
      "DAY TO DAY HYPERMARKET L.L.C",
      "AL MISBAH HYPERMARKET LLC",
      "DAY TO DAY GENERAL TRADING CENTER",
      "GIFT WAY GENERAL TRADING",
      "GIFT WAY GENERAL TRADING",
      "EMARATS MARKETS"
    ],
    Wednesday: [
      "GIFT ZONE TR",
      "MAKKAH MARKETS TR. LLC.- BRANCH 2",
      "EVERY DAY TR CENTER",
      "SAVING GIFTS CENTER LLC",
      "AL HOOT AL ABYDH SUPER MARKET LLC",
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ. BR",
      "NEW DAY CENTER TR LLC SP",
      "QASER AL KABAYEL GENERAL TRADING L.L.C",
      "DREAMS SEA DISCOUNT CENTRE"
    ],
    Thursday: [
      "CITY MARKET GROUP",
      "CITY MARKET GROUP",
      "WAHAT KALBA DISCOUNTS LLC",
      "WORLD GIFT TRADING EST",
      "MS MAX DISCOUNT CENTER",
      "NEW METRO MANILA SUPERMARKET LLC",
      "AL KABAEL DISCOUNT CENTER BRANCH 01"
    ],
    Friday: [
      "METRO MANILA SUPERMARKET BRANCH 1",
      "JANATA EXPRESS SUPERMARKET LLC",
      "ROYAL DISCOUNT CENTER LLC SOLE PROPRIETORSHIP",
      "BRAND MART GENERAL TRADING LLC BRANCH 01",
      "ADELA GENERAL TRADING LLC(SOLE PROPRIETORSHIP)",
      "DAY TO DAY INTERNATIONAL HYPERMARKET(AJMAN)",
      "CITY MAX GENERAL TRADING SPS LLC",
      "DAY TO DAY GENERAL TRADING CENTRE L.L.C(SOLE PROPRIETORSHIP)-BRANCH 01"
    ],
    Saturday: [
      "AL YASMEEN GROUP",
      "AL YASMEEN GROUP",
      "DELTA CENTRE TR LLC",
      "CM HYPERMARKET LLC",
      "GIFT MART GENERAL TRADING BRANCH 03",
      "PALM CENTRE"
    ],
    Sunday: []
   }
   ,"Week 2": {
    Monday: [
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ BR",
      "DREAM LAND DEPARTMENT STORE CENTER LLC",
      "AL WAHDA DISCOUNTS CENTRE",
      "KANZ AL BAHAR SUPERMARKET L.L.C",
      "GIFTS MARKET GEN.TRADING LLC",
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ BR-BRANCH 2",
      "CITY PLAZA TR",
      "DREAMS SEA DISCOUNT CENTRE"
    ],
    Tuesday: [
      "EMARATS MARKETS",
      "METRO MANILA SUPERMARKET BRANCH 1",
      "DAY TO DAY HYPERMARKET L.L.C",
      "AL MISBAH HYPERMARKET LLC",
      "DAY TO DAY GENERAL TRADING CENTER",
      "GIFT WAY GENERAL TRADING",
      "GIFT WAY GENERAL TRADING"
    ],
    Wednesday: [
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ BR",
      "METRO MANILA SUPERMARKET BRANCH 1",
      "DELTA CENTRE TR LLC",
      "EVERY DAY FRESH HYPERMARKET LLC",
      "SAVING GIFTS CENTER LLC",
      "PALENGKE TRADING L.L.C",
      "PHILIPPINO TOWN SUPERMARKET",
      "AL HOOT AL ABYDH SUPER MARKET LLC",
      "AL YASMEEN GROUP",
      "DELTA CENTRE TR LLC"
    ],
    Thursday: [
      "CITY MARKET GROUP",
      "CITY MARKET GROUP",
      "AL YASMEEN GROUP",
      "WAHAT KALBA DISCOUNTS LLC",
      "WORLD GIFT TRADING EST",
      "MS MAX DISCOUNT CENTER",
      "NEW METRO MANILA SUPERMARKET LLC",
      "AL MATJAR AL WATANI GENERAL TRADING (S.P.S-LLC)"
    ],
    Friday: [
      "METRO MANILA SUPERMARKET BRANCH 1",
      "DREAMS SEA DISCOUNT CENTRE",
      "ROYAL DISCOUNT CENTER LLC SOLE PROPRIETORSHIP",
      "BRAND MART GENERAL TRADING LLC BRANCH 01",
      "ADELA GENERAL TRADING LLC(SOLE PROPRIETORSHIP)",
      "DAY TO DAY INTERNATIONAL HYPERMARKET(AJMAN)",
      "CITY MAX GENERAL TRADING SPS LLC",
      "DAY TO DAY GENERAL TRADING CENTRE L.L.C(SOLE PROPRIETORSHIP)-BRANCH 01"
    ],
    Saturday: [
      "AL YASMEEN GROUP",
      "AL YASMEEN GROUP",
      "DELTA CENTRE TR LLC",
      "CM HYPERMARKET LLC",
      "GIFT MART GENERAL TRADING BRANCH 03",
      "PALM CENTRE"
    ],
    Sunday: []
  },

  "Week 3": {
    Monday: [
      "AL NAHDA GIFT CENTER",
      "NIGHT TO NIGHT DEPARTMENT STORE LLC BR",
      "DREAMS SEA DISCOUNT CENTRE",
      "FIRST DISCOUNTS CENTER",
      "ASWAQ AL SEYOUH GIFTS",
      "DEALS LAND DEPARTMENT STORE LLC SP",
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ.BR-BRANCH 3",
      "KANZ AL BAHAR SUPERMARKET L.L.C"
    ],
    Tuesday: [
      "BURMA SM",
      "METRO MANILA SUPERMARKET BRANCH 1",
      "DAY TO DAY HYPERMARKET L.L.C",
      "AL MISBAH HYPERMARKET LLC",
      "DAY TO DAY GENERAL TRADING CENTER",
      "GIFT WAY GENERAL TRADING",
      "GIFT WAY GENERAL TRADING",
      "EMARATS MARKETS"
    ],
    Wednesday: [
      "GIFT ZONE TR",
      "MAKKAH MARKETS TR. LLC.- BRANCH 2",
      "EVERY DAY TR CENTER",
      "SAVING GIFTS CENTER LLC",
      "ANWAR FLOUR MILL LLC",
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ. BR",
      "NEW DAY CENTER TR LLC SP",
      "CARRY FOOD SUPERMARKET LLC",
      "DREAMS SEA DISCOUNT CENTRE"
    ],
    Thursday: [
      "CITY MARKET GROUP",
      "AL YASMEEN GROUP",
      "AL MATJAR AL WATANI GENERAL TRADING (S.P.S-LLC)",
      "SENAN HYPERMARKET",
      "NOOR AL HAYATH HYPERMARLET LLC",
      "VARIETY SM",
      "LUCKY CENTER LLC",
      "LUCKY MARKETING&TRADING LLC"
    ],
    Friday: [
      "METRO MANILA SUPERMARKET BRANCH 1",
      "JANATA EXPRESS SUPERMARKET LLC",
      "ROYAL DISCOUNT CENTER LLC SOLE PROPRIETORSHIP",
      "BRAND MART GENERAL TRADING LLC BRANCH 01",
      "ADELA GENERAL TRADING LLC(SOLE PROPRIETORSHIP)",
      "DAY TO DAY INTERNATIONAL HYPERMARKET(AJMAN)",
      "CITY MAX GENERAL TRADING SPS LLC",
      "DAY TO DAY GENERAL TRADING CENTRE L.L.C(SOLE PROPRIETORSHIP)-BRANCH 01"
    ],
    Saturday: [
      "AL YASMEEN GROUP",
      "AL YASMEEN GROUP",
      "DELTA CENTRE TR LLC",
      "CM HYPERMARKET LLC",
      "GIFT MART GENERAL TRADING BRANCH 03",
      "PALM CENTRE"
    ],
    Sunday: []
  },

  "Week 4": {
    Monday: [
      "ATLAS TOWER GIFT CENTER LLC SOLE PROPRITETORSHIP",
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ BR",
      "DREAM LAND DEPARTMENT STORE CENTER LLC",
      "AL WAHDA DISCOUNTS CENTRE",
      "KANZ AL BAHAR SUPERMARKET L.L.C",
      "GIFTS MARKET GEN.TRADING LLC",
      "DREAMS SEA DISCOUNT CENTRE",
      "VILLAGE TOWER GIFTS - L L C",
      "PURE GOLD SUPERMARKET"
    ],
    Tuesday: [
      "CM HYPERMARKET LLC",
      "METRO MANILA SUPERMARKET BRANCH 1",
      "DAY TO DAY HYPERMARKET L.L.C",
      "AL MISBAH HYPERMARKET LLC",
      "EVERY DAY MALL LLC SOLE PROPRITORSHIP",
      "DAY TO DAY GENERAL TRADING CENTER",
      "EMARATS MARKETS",
      "CM HYPERMARKET LLC"
    ],
    Wednesday: [
      "DAY TO DAY INTERNATIONAL HYPERMARKET-SHJ BR",
      "WE SHOPPE GENERAL TRADING L L C - SHJ. BR",
      "DELTA CENTRE TR LLC",
      "GARDEN COSMETICS TR",
      "SAVING GIFTS CENTER LLC",
      "PALENGKE TRADING L.L.C",
      "PHILIPPINO TOWN SUPERMARKET",
      "AL HOOT AL ABYDH SUPER MARKET LLC",
      "DELTA CENTRE TR LLC"
    ],
    Thursday: [
      "CITY MARKET GROUP",
      "CITY MARKET GROUP",
      "AL YASMEEN GROUP",
      "WAHAT KALBA DISCOUNTS LLC",
      "WORLD GIFT TRADING EST",
      "MS MAX DISCOUNT CENTER",
      "NEW METRO MANILA SUPERMARKET LLC",
      "AL MATJAR AL WATANI GENERAL TRADING (S.P.S-LLC)"
    ],
    Friday: [
      "METRO MANILA SUPERMARKET BRANCH 1",
      "DREAMS SEA DISCOUNT CENTRE",
      "ROYAL DISCOUNT CENTER LLC SOLE PROPRIETORSHIP",
      "BRAND MART GENERAL TRADING LLC BRANCH 01",
      "ADELA GENERAL TRADING LLC(SOLE PROPRIETORSHIP)",
      "DAY TO DAY INTERNATIONAL HYPERMARKET(AJMAN)",
      "CITY MAX GENERAL TRADING SPS LLC",
      "DAY TO DAY GENERAL TRADING CENTRE L.L.C(SOLE PROPRIETORSHIP)-BRANCH 01"
    ],
    Saturday: [
      "AL YASMEEN GROUP",
      "AL YASMEEN GROUP",
      "DELTA CENTRE TR LLC",
      "CM HYPERMARKET LLC",
      "GIFT MART GENERAL TRADING BRANCH 03",
      "PALM CENTRE"
    ],
    Sunday: []
  }
 }
  ,Shaji: {
    "Week 1": {
      Monday: [
        "DAY TO DAY INTERNATIONAL DCC",
        "DAY TO DAY UNION",
        "DAY TO DAY INTERNATIONAL UNION2",
        "GREEN HOUSE INTERNATIONAL",
        "BASSAM CENTERE",
        "AL KABAYEL DISCOUNT CENTER",
        "PHILIPINE SUPER MARKET",
        "NEW PINOY MART",
        "DELTA TRADING",
        "PINOY CHOICE SUPERMARKET",
        "JANNATH AL MADINA"
      ],
      Tuesday: [
        "DAY TO DAY KARAMA",
        "G M CITY MART",
        "MADHOOR SUPERMARKET",
        "PHILPINE SUPERMARKET",
        "CENTRO ZOOM",
        "PALENGKE TRADING",
        "PINOY CHOICE SUPERMARKET",
        "PINOY GREENHOUSE",
        "PALENGKE TRADING"
      ],
      Wednesday: [
        "GREEN LAND HYPER MARKET",
        "NEW SHOPEE DEPARTMENT STORE",
        "HAFETH SUPERMARKET",
        "PINOY MART",
        "NEW PINOY MART",
        "AURA FAKHREE CENTRE",
        "DAY TO DAY FAHIDI",
        "ZAHRATH AL SHARQ",
        "COPPINS MINIMART",
        "BOLLY WOOD"
      ],
      Thursday: [
        "DAY TO DAY NAHDA1",
        "DAY TO DAY NAHDA2",
        "NAQAA AL MADINA",
        "DAWWAR AL MADINA",
        "MADINAT AL KABAYEL",
        "AL FALALAJ MARKET2",
        "FAMILA MAX DEPARTMENT STORE",
        "JANNATH AL MADINA",
        "MADINAT AL KABAYEL",
        "MOHIDEEN SUPER MARKET"
      ],
      Friday: [
        "QASAR AL KABAYEL",
        "BEST COOP DISCOUNT",
        "YAS HOME GENERAL TRADING",
        "BLUE MART HYPER MARKET",
        "BLUE MART SUPERMARKET",
        "JYUBILY TRADING",
        "AL KABAYEL OASIS",
        "DAY TO DAY SAFA",
        "GIFT CITY GENERAL TRADING",
        "HAMAIDI DEPARTMENTSTORE"
      ],
      Saturday: [
        "AVANUE BY DAY TO DAY",
        "247 MINI MART",
        "FRESHDAY SUPERMARKET",
        "GREEN BASKET",
        "BEST BUY SUPERMARKET",
        "UNIQUE TOWER",
        "FINE TOWER SUPERMARKET",
        "NEW DELMA SUPERMARKET",
        "GATEPLUS SUPER MARKET"
      ],
      Sunday: []
    },
    "Week 2": {
    Monday: [
      "DAY TO DAY BANIYAS",
      "DREAM LAND",
      "NIGHT TO NIGHT",
      "GIFT POINT",
      "CARRY FOOD SUPER MARKET",
      "UNITED HYPERMARKET",
      "1TO10 CENTRE",
      "GREEN LAND HYPERMARKET",
      "G SEVEN HYPERMARKET",
      "ALFALAJ MARKET",
      "QASAR AL KABAYEL",
      "YADA GROCERY",
      "DREAM LAND DEPARTMENT STORE CENTER LLC"
    ],
    Tuesday: [
      "DAY TO DAY KARAMA",
      "FRESH COPPINS",
      "MADHOOR SUPERMARKET",
      "PHILPINE SUPERMARKET",
      "CENTRO ZOOM",
      "DAY TO DAY GENERAL TRD",
      "PINOY CHOICE SUPERMARKET",
      "PINOY GREENHOUSE",
      "STAR KADOOLI",
      "CARRYFOOD SUPERMARKET"
    ],
    Wednesday: [
      "GREEN LAND HYPER MARKET",
      "NEW SHOPEE DEPARTMENT STORE",
      "HAFETH SUPERMARKET",
      "PINOY MART",
      "NEW PINOY MART",
      "DAY TO DAY FAHIDI",
      "ZAHRATH AL SHARQ",
      "HOLLY WOOD",
      "COPPINS MINIMART",
      "BEAUTY NIGHT GENERAL TRADING",
      "DREAM NIGHT"
    ],
    Thursday: [
      "DAY TO DAY NAHDA1",
      "DAY TO DAY NAHDA2",
      "NAQAA AL MADINA",
      "DAWWAR AL MADINA",
      "MADINAT AL KABAYEL",
      "AL FALALAJ MARKET2",
      "FAMILA MAX MART",
      "KOOIK MART",
      "BLUE MART FRESH",
      "QASAR AL KABAYEL"
    ],
    Friday: [
      "PALENGKE TRADING",
      "INAYAH TRADING",
      "TRADESKY FOOD TRADING",
      "BLUE MART SUPERMARKET",
      "JYUBILY TRADING",
      "AL KABAYEL OASIS",
      "DAY TO DAY SAFA",
      "GREEN GIFT DEWPARTMET STORE",
      "BLUE MART HYPER MARKET",
      "KADOOLI SUPERMARKET",
      "GREEN PARK SUPERMARKET"
    ],
    Saturday: [
      "AVANUE BY DAY TO DAY",
      "NEW DELMA SUPERMARKET",
      "FRESHDAY SUPERMARKET",
      "GREEN BASKET",
      "BEST BUY SUPERMARKET",
      "UNIQUE TOWER",
      "FINE TOWER SUPERMARKET",
      "GATEPLUS SUPER MARKET",
      "247 MINI MART"
    ],
    Sunday: []
  },

  "Week 3": {
    Monday: [
      "DAY TO DAY INTERNATIONAL DCC",
      "DAY TO DAY UNION",
      "DAY TO DAY INTERNATIONAL UNION2",
      "GREEN HOUSE INTERNATIONAL",
      "BASSAM CENTERE",
      "AL KABAYEL DISCOUNT CENTER",
      "PHILIPINE SUPER MARKET",
      "NEW PINOY MART",
      "DELTA TRADING",
      "BLUE SPEED WAY MINI MART",
      "FRUIT GIFTLAND",
      "DELMA FRESH MINIMART"
    ],
    Tuesday: [
      "DAY TO DAY KARAMA",
      "G M CITY MART",
      "MADHOOR SUPERMARKET",
      "PHILPINE SUPERMARKET",
      "CENTRO ZOOM GENERALTRADING",
      "PALENGKE TRADING",
      "PINOY CHOICE SUPERMARKET",
      "PINOY GREENHOUSE",
      "CARRYFOOD SUPERMARKET",
      "STAR KADOOLI"
    ],
    Wednesday: [
      "GREEN LAND HYPER MARKET",
      "NEW SHOPEE DEPARTMENT STORE",
      "HAFETH SUPERMARKET",
      "PINOY MART",
      "NEW PINOY MART",
      "AURA FAKHREE CENTRE",
      "DAY TO DAY FAHIDI",
      "ZAHRATH AL SHARQ",
      "COPPINS MINIMART",
      "HOLLY WOOD",
      "BEAUTY NIGHT GENERAL TRADING"
    ],
    Thursday: [
      "DAY TO DAY NAHDA1",
      "DAY TO DAY NAHDA2",
      "NAQAA AL MADINA",
      "DAWWAR AL MADINA",
      "MADINAT AL KABAYEL",
      "AL FALALAJ MARKET2",
      "FAMILA MAX MART",
      "JANNATH AL MADINA",
      "MADINAT AL KABAYEL",
      "MOHIDEEN SUPER MARKET"
    ],
    Friday: [
      "QASAR AL KABAYEL",
      "BEST COOP DISCOUNT",
      "BLUE MART FRESH MINI MART LLC (BRANCH)",
      "BLUE MARTHYPER MARKET",
      "BLUE MART SUPERMARKET",
      "JYUBILY TRADING",
      "KABAYEL OASIS",
      "DAY TO DAY SAFA",
      "GIFT CITY GENERAL TRADING",
      "HAMAIDI DEPARTMENTSTORE",
      "D S G GENERAL TRADING LLC",
      "IMAGO WHOLSALE TRADING LLC"
    ],
    Saturday: [
      "AVANUE BY DAY TO DAY",
      "247 MINI MART",
      "FRESHDAY SUPERMARKET",
      "GREEN BASKET",
      "BEST BUY SUPERMARKET",
      "UNIQUE TOWER",
      "FINE TOWER SUPERMARKET",
      "NEW DELMA SUPERMARKET",
      "GATEPLUS SUPER MARKET"
    ],
    Sunday: []
  },

  "Week 4": {
    Monday: [
      "DAY TO DAY INTERNATIONAL DCC",
      "DAY TO DAY UNION",
      "DAY TO DAY INTERNATIONAL UNION2",
      "GREEN HOUSE INTERNATIONAL",
      "BASSAM CENTERE",
      "AL KABAYEL DISCOUNT CENTER",
      "PHILIPINE SUPER MARKET",
      "NEW PINOY MART",
      "DELTA TRADING",
      "PINOY CHOICE SUPERMARKET",
      "JANNATH AL MADINA",
      "GIFT LAND DEPARTMENTSTORE"
    ],
    Tuesday: [
      "DAY TO DAY KARAMA",
      "G M CITY MART",
      "MADHOOR SUPERMARKET",
      "PHILPINE SUPERMARKET",
      "CENTRO ZOOM GENERALTRADING",
      "PALENGKE TRADING",
      "PINOY CHOICE SUPERMARKET",
      "PINOY GREENHOUSE SUPERMARKET",
      "CARRYFOOD SUPERMARKET",
      "STAR KADOOLI"
    ],
    Wednesday: [
      "GREEN LAND HYPER MARKET",
      "NEW SHOPEE DEPARTMENT STORE",
      "HAFETH SUPERMARKET",
      "PINOY MART",
      "NEW PINOY MART",
      "AURA FAKHREE CENTRE",
      "DAY TO DAY FAHIDI",
      "ZAHRATH AL SHARQ",
      "COPPINS MINIMART",
      "HOLLY WOOD",
      "BEAUTY NIGHT GENERAL TRADING",
      "PINOY MART LLC"
    ],
    Thursday: [
      "DAY TO DAY NAHDA1",
      "DAY TO DAY NAHDA2",
      "NAQAA AL MADINA",
      "DAWWAR AL MADINA",
      "MADINAT AL KABAYEL",
      "AL FALALAJ MARKET2",
      "KOOIK MART",
      "JANNATH AL MADINA",
      "MADINAT AL KABAYEL",
      "MOHIDEEN SUPER MARKET",
      "BLUE MART FRESH",
      "KG FOODSTUFF TRADING COMPANY FZCO"
    ],
    Friday: [
      "QASAR AL KABAYEL",
      "BEST COOP DISCOUNT",
      "BLUE MART HYPER MARKET",
      "BLUE MART SUPERMARKET",
      "JYUBILY TRADING",
      "KABAYEL OASIS",
      "DAY TO DAY HYPERMARKET",
      "GIFT CITY GENERAL TRADING",
      "HAMAIDI DEPARTMENTSTORE",
      "NEW ANGEL GENRAL TRADING LLC",
      "QASER AL KABAYEL GENERAL TRADING L.L.C"
    ],
    Saturday: [
      "AVANUE BY DAY TO DAY",
      "247 MINI MART",
      "FRESHDAY SUPERMARKET",
      "GREEN BASKET",
      "BEST BUY SUPERMARKET",
      "UNIQUE TOWER",
      "FINE TOWER SUPERMARKET",
      "NEW DELMA SUPERMARKET",
      "GATEPLUS SUPER MARKET"
    ],
    Sunday: []
  }
  },
  Imtiaz: {
    "Week 1": {
    Monday: [
      "ZENITH SUPERMARKET",
      "ZENITH SUPERMARKET",
      "SEA BIRD SUPERMARKET - L L C - BRANCH 2",
      "NOOR BANIYAS SUPERMARKET",
      "THREE STAR FASHIONS WLL",
      "ZENITH SUPERMARKET",
      "NOOR AL IZDIHAR SUPERMARKET LLC",
      "SHABIA ALMADEENA SUPERMARKET LLC OPC",
      "AL TAYEF SM",
      "GREEN APPLE SM",
      "SM FRESH BARK-SOLE PROPRIETORSHIP LLC",
      "DISCOUNT PLUS GIFTS-SOLE PROPRIETORSHIP L.L.C",
      "TUWARISH SUPERMARKET",
      "JAHANGHIR ALAM HOUSEHOLD MATERIALS LLC"
    ],
    Tuesday: [
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "GIFT CITY",
      "JIMI GIFT MARKET",
      "REFA GIFTS MARKET LLC",
      "NAJEM MUBARAK SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "GREEN LIWA SM ROASTER&FM",
      "ONE LAND HYPERMARKET LLC",
      "WELCOME WORLD TRADING",
      "WORLD PRODUCTS GENERAL",
      "TEN MARKET",
      "CITY NAS"
    ],
    Wednesday: [
      "FILIPINO HOUSE SUPERMARKET LLC",
      "FILIPINO HOUSE SUPERMARKET LLC",
      "KABAYAN HOUSE BAQALA",
      "KABAYAN HOUSE BAQALA",
      "GREEN HOUSE BAQALA",
      "MAJESTIC SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "HOME FRESH SUPERMARKET LLC",
      "DAY MART HYPERMARKET LLC",
      "EASY MART HYPER MARKET",
      "MAJESTIC PLUS HYPERMARKET LLC",
      "MAJESTIC SUPERMARKET",
      "MECADO TRADING LLC",
      "EVERY DAY DISCOUNT MARKET LLC"
    ],
    Thursday: [
      "FAB MART SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "AL HILI GIFT MARKET LLC OPC",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "ABU AHMED TRADING",
      "AL TAMAYOZ HYPERMARKET",
      "AL TAMAYOZ HYPERMARKET",
      "TARIF SUPERMARKET",
      "ONE LAND HYPERMARKET LLC",
      "PALENGKE TRADING LLC",
      "PALENGKE TRADING LLC",
      "LEPTIS HYPERMARKET LLC"
    ],
    Friday: [
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "ONE TO TEN GIFTS - SOLE PROPRIETORSHIP LLC",
      "ROYAL GIFTS COLLECTION",
      "CARRYONE HYPERMARKET LLC",
      "DAY TO DAY HYPERMARKET LLC BRANCH ABU DHABI 1",
      "FUTURE STAR SUPERMARKET LLC",
      "GRAND MAJESTIC HYPERMARKET LLC",
      "BARTER HYPERMARKET LLC",
      "247 SUPERMARKET LLC",
      "247 FRESH AND COOL SUPERMARKET LLC",
      "GIFT WAY GENERAL TRADING",
      "SIDDIQ GIFTS LLC",
      "RED STAR GIFTS - BRANCH 1"
    ],
    Saturday: [
      "GRAND EMIRATES MARKET LLC",
      "GRAND EMIRATES MARKET LLC",
      "THREE STAR FASHIONS WLL",
      "KABAYAN HOUSE BAQALA",
      "KABAYAN HOUSE BAQALA",
      "GREEN HOUSE BAQALA",
      "METRO MANILA HYPERMARKET - BR OF ABU DHABI",
      "METRO MANILA HYPERMARKET - BR OF ABU DHABI",
      "DISCOUNT PLUS GIFTS - SOLE PROPRIETORSHIP LLC",
      "PURE BROWN CHOCOLATES LLC",
      "TOURIST AL MADEENA HYPERMARKET LLC",
      "TOURIST AL MADEENA SUPERMARKET",
      "BARTER HYPERMARKET LLC"
    ],
    Sunday: []
  },
  "Week 2": {
    Monday: [
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "GIFT CITY",
      "JIMI GIFT MARKET",
      "REFA GIFTS MARKET LLC",
      "NAJEM MUBARAK SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "GREEN LIWA SM ROASTER&FM",
      "ONE LAND HYPERMARKET LLC"
    ],
    Tuesday: [
      "ZENITH SUPERMARKET",
      "ZENITH SUPERMARKET",
      "SEA BIRD SUPERMARKET - L L C - BRANCH 2",
      "NOOR BANIYAS SUPERMARKET",
      "THREE STAR FASHIONS WLL",
      "ZENITH SUPERMARKET",
      "NOOR AL IZDIHAR SUPERMARKET LLC",
      "SHABIA ALMADEENA SUPERMARKET LLC OPC",
      "AL TAYEF SM",
      "GREEN APPLE SM",
      "SM FRESH BARK-SOLE PROPRIETORSHIP LLC",
      "DISCOUNT PLUS GIFTS-SOLE PROPRIETORSHIP L.L.C",
      "TUWARISH SUPERMARKET"
    ],
    Wednesday: [
      "FAB MART SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "AL HILI GIFT MARKET LLC OPC",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "ABU AHMED TRADING",
      "AL TAMAYOZ HYPERMARKET",
      "AL TAMAYOZ HYPERMARKET",
      "TARIF SUPERMARKET",
      "ONE LAND HYPERMARKET LLC",
      "DAY MART HYPERMARKET LLC"
    ],
    Thursday: [
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "ONE TO TEN GIFTS",
      "ROYAL GIFTS COLLECTION",
      "CARRYONE HYPERMARKET LLC",
      "DAY TO DAY HYPERMARKET LLC ABU DHABI 1",
      "FUTURE STAR SUPERMARKET LLC",
      "GRAND MAJESTIC HYPERMARKET LLC",
      "BARTER HYPERMARKET LLC",
      "247 SUPERMARKET LLC",
      "247 FRESH AND COOL SUPERMARKET LLC",
      "GIFT WAY GENERAL TRADING"
    ],
    Friday: [
      "FILIPINO HOUSE SUPERMARKET LLC",
      "FILIPINO HOUSE SUPERMARKET LLC",
      "KABAYAN HOUSE BAQALA",
      "KABAYAN HOUSE BAQALA",
      "GREEN HOUSE BAQALA",
      "MAJESTIC SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "HOME FRESH SUPERMARKET LLC",
      "DAY MART HYPERMARKET LLC"
    ],
    Saturday: [
      "FAB MART SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "AL HILI GIFT MARKET LLC OPC",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "ABU AHMED TRADING",
      "AL TAMAYOZ HYPERMARKET",
      "AL TAMAYOZ HYPERMARKET",
      "TARIF SUPERMARKET",
      "ONE LAND HYPERMARKET LLC",
      "GIFT WAY GENERAL TRADING"
    ]
  },

  "Week 3": {
    Monday: [
      "ZENITH SUPERMARKET",
      "ZENITH SUPERMARKET",
      "SEA BIRD SUPERMARKET - BRANCH 2",
      "NOOR BANIYAS SUPERMARKET",
      "THREE STAR FASHIONS WLL",
      "ZENITH SUPERMARKET",
      "NOOR AL IZDIHAR SUPERMARKET LLC",
      "SHABIA ALMADEENA SUPERMARKET LLC OPC",
      "AL TAYEF SM",
      "GREEN APPLE SM",
      "SM FRESH BARK",
      "DISCOUNT PLUS GIFTS",
      "TUWARISH SUPERMARKET",
      "JAHANGHIR ALAM HOUSEHOLD MATERIALS LLC"
    ],
    Tuesday: [
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "GIFT CITY",
      "JIMI GIFT MARKET",
      "REFA GIFTS MARKET LLC",
      "NAJEM MUBARAK SUPERMARKET LLC",
      "LOTUS STAR GIFTS",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "GREEN LIWA SM ROASTER&FM",
      "ONE LAND HYPERMARKET LLC",
      "WELCOME WORLD TRADING",
      "WORLD PRODUCTS GENERAL",
      "TEN MARKET",
      "CITY NAS"
    ],
    Wednesday: [
      "FILIPINO HOUSE SUPERMARKET LLC",
      "FILIPINO HOUSE SUPERMARKET LLC",
      "KABAYAN HOUSE BAQALA",
      "KABAYAN HOUSE BAQALA",
      "GREEN HOUSE BAQALA",
      "MAJESTIC SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "HOME FRESH SUPERMARKET LLC",
      "DAY MART HYPERMARKET LLC",
      "EASY MART HYPER MARKET",
      "MAJESTIC PLUS HYPERMARKET LLC",
      "MECADO TRADING LLC",
      "EVERY DAY DISCOUNT MARKET LLC"
    ],
    Thursday: [
      "FAB MART SUPERMARKET LLC",
      "LOTUS STAR GIFTS",
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "AL HILI GIFT MARKET LLC OPC",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "ABU AHMED TRADING",
      "AL TAMAYOZ HYPERMARKET",
      "AL TAMAYOZ HYPERMARKET",
      "TARIF SUPERMARKET",
      "ONE LAND HYPERMARKET LLC",
      "PALENGKE TRADING LLC",
      "LEPTIS HYPERMARKET LLC"
    ],
    Friday: [
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "ONE TO TEN GIFTS",
      "ROYAL GIFTS COLLECTION",
      "CARRYONE HYPERMARKET LLC",
      "DAY TO DAY HYPERMARKET LLC",
      "FUTURE STAR SUPERMARKET LLC",
      "GRAND MAJESTIC HYPERMARKET LLC",
      "BARTER HYPERMARKET LLC",
      "247 SUPERMARKET LLC",
      "247 FRESH AND COOL SUPERMARKET LLC",
      "GIFT WAY GENERAL TRADING",
      "SIDDIQ GIFTS LLC"
    ],
    Saturday: [
      "GRAND EMIRATES MARKET LLC",
      "GRAND EMIRATES MARKET LLC",
      "THREE STAR FASHIONS WLL",
      "KABAYAN HOUSE BAQALA",
      "KABAYAN HOUSE BAQALA",
      "GREEN HOUSE BAQALA",
      "METRO MANILA HYPERMARKET",
      "METRO MANILA HYPERMARKET",
      "DISCOUNT PLUS GIFTS",
      "PURE BROWN CHOCOLATES LLC",
      "TOURIST AL MADEENA HYPERMARKET LLC",
      "TOURIST AL MADEENA SUPERMARKET",
      "BARTER HYPERMARKET LLC"
    ]
  },

  "Week 4": {
    Monday: [
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "GIFT CITY",
      "JIMI GIFT MARKET",
      "REFA GIFTS MARKET LLC",
      "NAJEM MUBARAK SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "GREEN LIWA SM ROASTER&FM",
      "ONE LAND HYPERMARKET LLC"
    ],
    Tuesday: [
      "ZENITH SUPERMARKET",
      "ZENITH SUPERMARKET",
      "SEA BIRD SUPERMARKET - BRANCH 2",
      "NOOR BANIYAS SUPERMARKET",
      "THREE STAR FASHIONS WLL",
      "ZENITH SUPERMARKET",
      "NOOR AL IZDIHAR SUPERMARKET LLC",
      "SHABIA ALMADEENA SUPERMARKET LLC OPC",
      "AL TAYEF SM",
      "GREEN APPLE SM",
      "SM FRESH BARK",
      "DISCOUNT PLUS GIFTS",
      "TUWARISH SUPERMARKET"
    ],
    Wednesday: [
      "FAB MART SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "AL HILI GIFT MARKET LLC OPC",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "ABU AHMED TRADING",
      "AL TAMAYOZ HYPERMARKET",
      "AL TAMAYOZ HYPERMARKET",
      "TARIF SUPERMARKET",
      "ONE LAND HYPERMARKET LLC",
      "DAY MART HYPERMARKET LLC"
    ],
    Thursday: [
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "THREE STAR FASHIONS WLL",
      "ONE TO TEN GIFTS",
      "ROYAL GIFTS COLLECTION",
      "CARRYONE HYPERMARKET LLC",
      "DAY TO DAY HYPERMARKET LLC",
      "FUTURE STAR SUPERMARKET LLC",
      "GRAND MAJESTIC HYPERMARKET LLC",
      "BARTER HYPERMARKET LLC",
      "247 SUPERMARKET LLC",
      "GIFT WAY GENERAL TRADING"
    ],
    Friday: [
      "FILIPINO HOUSE SUPERMARKET LLC",
      "FILIPINO HOUSE SUPERMARKET LLC",
      "KABAYAN HOUSE BAQALA",
      "KABAYAN HOUSE BAQALA",
      "GREEN HOUSE BAQALA",
      "MAJESTIC SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "JANNATH AL MADINA SUPERMARKET",
      "HOME FRESH SUPERMARKET LLC",
      "DAY MART HYPERMARKET LLC"
    ],
    Saturday: [
      "FAB MART SUPERMARKET LLC",
      "LOTUS STAR GIFTS - BRANCH 1",
      "CITY AVENUE SHOPPING CENTER LLC OPC",
      "AL AIN GIFT MARKETS",
      "AL AIN FLOWER MARKET LLC",
      "AL HILI GIFT MARKET LLC OPC",
      "AL AYILA MARKET DISCOUNT LLC OPC",
      "ABU AHMED TRADING",
      "AL TAMAYOZ HYPERMARKET",
      "AL TAMAYOZ HYPERMARKET",
      "TARIF SUPERMARKET",
      "ONE LAND HYPERMARKET LLC",
      "GIFT WAY GENERAL TRADING"
    ]
  }
  },
  Arshad: {
    "Week 1": {
      Monday: [
        "WAHAT KALABA DISCOUNT",
        "PALM DISCOUNT CENTER",
        "CITY MARKET",
        "AL TAQDEER PLAZA",
        "AL TAQDEER DISCOUNT CENTER",
        "EMIRATES GALLERY DISCOUNT"
      ],
      Tuesday: [
        "LEPTIS HYPER",
        "LEPTIS FRESH",
        "TOP 20",
        "SUN AND SAND HYPER",
        "EMIRATES SM",
        "MARJAN GALLERY DISCOUNT",
        "METRO MANILA SM",
        "MS MAX"
      ],
      Wednesday: [
        "20 PLAZA",
        "EMIRATES GALLERY",
        "TOP 10",
        "ALI BABA DISCOUNT MARKET",
        "SAMA AL KHALEEJ",
        "EMIRATES GALLERY DISCOUNT",
        "EVERY DAY CENTER"
      ],
      Thursday: [
        "PALM DISCOUNT CENTER",
        "JOINT TR",
        "BIDIYA SM",
        "CAPITAL SM",
        "JOINT TR",
        "JOINT TR"
      ],
      Friday: [
        "ALI BABA DISCOUNT",
        "ALI BABA DISCOUNT",
        "AL KHALEEJ MARKET",
        "EMIRATES DISCOUNT MARKET",
        "SUN AND SAND DISCOUNT"
      ],
      Saturday: [
        "CITY MARKET",
        "EMIRATES GALLERY DISCOUNT",
        "METRO MANILA SM",
        "REEM HYPER",
        "ALI BABA DISCOUNT MARKET",
        "20 PLAZA"
      ]
    },
  
    "Week 2": {
      Monday: [
        "WAHAT KALABA DISCOUNT",
        "PALM DISCOUNT CENTER",
        "CITY MARKET",
        "AL TAQDEER PLAZA",
        "AL TAQDEER DISCOUNT CENTER",
        "EMIRATES GALLERY DISCOUNT"
      ],
      Tuesday: [
        "WORLD DISCOUNT MARKET",
        "EMIRATES GALLERY",
        "TOP 20",
        "AL KHALEEJ MARKET",
        "DAY TO DAY TRADING",
        "VALUE BAG",
        "METRO MANILA SM"
      ],
      Wednesday: [
        "20 PLAZA",
        "EMIRATES GALLERY",
        "TOP 10",
        "ALI BABA DISCOUNT MARKET",
        "SAMA AL KHALEEJ",
        "EMIRATES GALLERY DISCOUNT",
        "EVERY DAY CENTER"
      ],
      Thursday: [
        "PALM DISCOUNT CENTER",
        "JOINT TR",
        "BIDIYA SM",
        "CAPITAL SM",
        "JOINT TR",
        "JOINT TR"
      ],
      Friday: [
        "ALI BABA DISCOUNT",
        "ALI BABA DISCOUNT",
        "AL KHALEEJ MARKET",
        "EMIRATES DISCOUNT MARKET",
        "SUN AND SAND DISCOUNT"
      ],
      Saturday: [
        "CITY MARKET",
        "EMIRATES GALLERY DISCOUNT",
        "METRO MANILA SM",
        "REEM HYPER",
        "ALI BABA DISCOUNT MARKET",
        "20 PLAZA"
      ]
    },
  
    "Week 3": {
      Monday: [
        "WAHAT KALABA DISCOUNT",
        "PALM DISCOUNT CENTER",
        "CITY MARKET",
        "AL TAQDEER PLAZA",
        "AL TAQDEER DISCOUNT CENTER",
        "EMIRATES GALLERY DISCOUNT"
      ],
      Tuesday: [
        "LEPTIS HYPER",
        "LEPTIS FRESH",
        "TOP 20",
        "SUN AND SAND HYPER",
        "EMIRATES SM",
        "MARJAN GALLERY DISCOUNT",
        "METRO MANILA SM",
        "MS MAX"
      ],
      Wednesday: [
        "20 PLAZA",
        "EMIRATES GALLERY",
        "TOP 10",
        "ALI BABA DISCOUNT MARKET",
        "SAMA AL KHALEEJ",
        "EMIRATES GALLERY DISCOUNT",
        "EVERY DAY CENTER"
      ],
      Thursday: [
        "PALM DISCOUNT CENTER",
        "JOINT TR",
        "BIDIYA SM",
        "CAPITAL SM",
        "JOINT TR",
        "JOINT TR"
      ],
      Friday: [
        "ALI BABA DISCOUNT",
        "ALI BABA DISCOUNT",
        "AL KHALEEJ MARKET",
        "EMIRATES DISCOUNT MARKET",
        "SUN AND SAND DISCOUNT"
      ],
      Saturday: [
        "CITY MARKET",
        "EMIRATES GALLERY DISCOUNT",
        "METRO MANILA SM",
        "REEM HYPER",
        "ALI BABA DISCOUNT MARKET",
        "20 PLAZA"
      ]
    },
  
    "Week 4": {
      Monday: [
        "WAHAT KALABA DISCOUNT",
        "PALM DISCOUNT CENTER",
        "CITY MARKET",
        "AL TAQDEER PLAZA",
        "AL TAQDEER DISCOUNT CENTER",
        "EMIRATES GALLERY DISCOUNT"
      ],
      Tuesday: [
        "WORLD DISCOUNT MARKET",
        "EMIRATES GALLERY",
        "TOP 20",
        "AL KHALEEJ MARKET",
        "DAY TO DAY TRADING",
        "VALUE BAG",
        "METRO MANILA SM"
      ],
      Wednesday: [
        "20 PLAZA",
        "EMIRATES GALLERY",
        "TOP 10",
        "ALI BABA DISCOUNT MARKET",
        "SAMA AL KHALEEJ",
        "EMIRATES GALLERY DISCOUNT",
        "EVERY DAY CENTER"
      ],
      Thursday: [
        "PALM DISCOUNT CENTER",
        "JOINT TR",
        "BIDIYA SM",
        "CAPITAL SM",
        "JOINT TR",
        "JOINT TR"
      ],
      Friday: [
        "ALI BABA DISCOUNT",
        "ALI BABA DISCOUNT",
        "AL KHALEEJ MARKET",
        "EMIRATES DISCOUNT MARKET",
        "SUN AND SAND DISCOUNT"
      ],
      Saturday: [
        "CITY MARKET",
        "EMIRATES GALLERY DISCOUNT",
        "METRO MANILA SM",
        "REEM HYPER",
        "ALI BABA DISCOUNT MARKET",
        "20 PLAZA"
      ]
    }
  },
  Shabeeb: {
    "Week 1": {
    Monday: [
      "PLUS POINT SUPERMARKET",
      "CARRY FOOD MINI MART",
      "PLUS POINT EXP MART LLC",
      "FRESH PLUS POINT SM",
      "FRESH PLUS POINT SM",
      "BEACH WAVES SUPERMARKET LLC",
      "BEACH CITY SUPERMARKET LLC",
      "CARAMEL CENTER LLC",
      "MACRO SUPERMARKET LLC",
      "MACRO SUPERMARKET LLC",
      "MACRO SUPERMARKET LLC",
      "GOOD DAY SUPERMARKET LLC",
      "FOOD CENTER SUPERMARKET LLC"
    ],
    Tuesday: [
      "CITY SPEED WAY SUPERMARKET LLC",
      "AL KABAYEL DISCOUNT CENTRE",
      "AL AJWA MINIMART LLC",
      "SPEED WAY MM",
      "SPEED WAY MM 2",
      "GOOD DAY SUPERMARKET LLC",
      "EXPRESS BLUE MART LLC",
      "ROUND THE CLOCK MINI MART",
      "AL KABAYEL OASIS TRADING",
      "GREEN PLUS SUPER MARKET LLC"
    ],
    Wednesday: [
      "AFSHA MINI MART LLC",
      "NEW TUDO MART SUPERMARKET",
      "YASS SUPERMARKET LLC",
      "DELTA TRADING CENTER LLC",
      "KP INTERNATIONAL GENERAL TRADING LLC",
      "AFSHA MINI MART LLC",
      "ALKABAYEL PRIME TRADING LLC",
      "GREENS MINI MART",
      "EVER FRESH MART SUPERMARKET LLC",
      "SMILEON SUPERMARKET LLC",
      "LOFT MINI MART",
      "ICEBERG GROCERY LLC",
      "APPLE A DAY SUPERMARKET LLC",
      "TRUST VALUE SUPERMARKET LLC"
    ],
    Thursday: [
      "MACRO SUPERMARKET LLC",
      "BLUE BERRY MINI MART",
      "GRAND BARSHA DEPARTMENT STORES LLC",
      "PALENGKE TRADING LLC",
      "NEW METRO MANILA SUPERMARKET LLC",
      "DAY TO DAY GENERAL TRADING CENTER LLC",
      "DAY TO DAY INTERNATIONAL TRADING LLC",
      "GRAND MULTIMART SUPERMARKET LLC",
      "GOLDEN KABAB RESTAURANT EST"
    ],
    Friday: [
      "CARRY FOOD MINI MART",
      "AL AFNAN GRO J ALI",
      "BURJ ALSAFA MINI MART LLC",
      "DANAT EXPRESS SUPERMARKET LLC",
      "DANAT SUPERMARKET LLC",
      "AL BARARI MINI MART LLC",
      "NEEDS AND FRESH MINI MART LLC",
      "LOFT MINI MART LLC",
      "GOOD DAY SUPERMARKET LLC",
      "BLOOMS STAR MINI MART CO LLC",
      "HOPINZ SUPERMARKET LLC",
      "STAR MART CONVENIENCE STORE LLC"
    ],
    Saturday: [
      "SARVE MART JLT",
      "JOUDI MINI MART",
      "MANILA MART",
      "AURA FRESH DMCC",
      "GRABADELI FRESH & HEALTHY",
      "GRABADELI DMCC SUPERMARKET",
      "MOHED GROCERY DMCC",
      "NOUR FRESH MART DMCC",
      "BEST BUY SUPERMARKET LLC",
      "BIG BUY MARKET DMCC",
      "VUNDERS DMCC"
    ]
  },

  "Week 2": {
    Monday: [
      "SEVEN PLUS SUPERMARKET CO LLC",
      "FRESH MORE MINI MART LLC",
      "CARRY FOOD MINI MART LLC",
      "PLUS POINT MINI MART",
      "FRESH CARE MINI MART",
      "MARINA KP MART LLC",
      "MARINA SUITS SUPERMARKET LLC",
      "SPEEDWAY MARKET SUPERMARKET LLC",
      "SPEEDWAY MARKET SUPERMARKET LLC",
      "BUY MORE SUPERMARKET LLC",
      "CARRY FOOD SUPERMARKET LLC",
      "CARRY FOOD SUPERMARKET LLC"
    ],
    Tuesday: [
      "ONLINE GRO MEDIA CITY",
      "FRESH WAY MINI MART",
      "STRIPES SM",
      "FULL BASKET SUPERMARKET LLC",
      "J A I MINIMART FZ LLC",
      "FRESH WAY MINI MART LLC",
      "K P MART MINI MART LLC",
      "FULL STAR SUPERMARKET LLC",
      "CENTURY HARVEST SUPERMARKET LLC",
      "SUFOUH GARDENS SUPERMARKET LLC",
      "THE WOODEN SPOON RESTAURANT LLC",
      "SELLA MINI MART FZ LLC",
      "SHANDIZ PALACE RESTAURANT EST"
    ],
    Wednesday: [
      "FULL CART MINI MART LLC",
      "STAR MART SUPERMARKET LLC",
      "RENEE SUPERMARKET LLC",
      "RENEE SUPERMARKET LLC",
      "BEST BUY SUPERMARKET LLC",
      "SEVEN MARKET LLC",
      "BEST HOME MARKET LLC",
      "ALL SEASON MINI MART LLC",
      "BERRIES MINI MART LLC",
      "ATLANTICS SUPERMARKET LLC",
      "DAY PICK MINI MART LLC",
      "BEST IN VILLAGE SUPERMARKET LLC",
      "ZAYTUN SAHARA MINI MART LLC",
      "PALM TREE MINI MART",
      "SHOPRITE MINI MART FZCO"
    ],
    Thursday: [
      "LOYAL MINI MART LLC",
      "CARRYFOOD FRESH MINI MART LLC",
      "HEARTLAND SUPERMARKET LLC",
      "OMRAN ALJASMI GROCERY LLC",
      "ASAS AL MADINA SUPERMARKET LLC",
      "BIGBUY EXPRESS SUPERMARKET LLC",
      "AL TANAFUS GROCERY STORE LLC",
      "LOFT MINI MART LLC"
    ],
    Friday: [
      "BLUE MART FRESH MINI MART LLC",
      "BLUE MART FRESH MINI MART LLC"
    ],
    Saturday: [
      "FULL CART SUPERMARKET LLC",
      "CARRY FOOD PLUS MINI MART LLC",
      "FULL CART MINI MART LLC",
      "FRESH BASKET SUPERMARKET LLC",
      "FOR LEO GOURMET MINI MART LLC",
      "ALBASHAYER MINI MART LLC"
    ]
  },

  "Week 3": {
    Monday: [
      "PLUS POINT SUPERMARKET",
      "CARRY FOOD MINI MART",
      "PLUS POINT EXP MART LLC",
      "FRESH PLUS POINT SM",
      "FRESH PLUS POINT SM",
      "BEACH WAVES SUPERMARKET LLC",
      "BEACH CITY SUPERMARKET LLC",
      "CARAMEL CENTER LLC",
      "MACRO SUPERMARKET LLC",
      "MACRO SUPERMARKET LLC",
      "MACRO SUPERMARKET LLC",
      "GOOD DAY SUPERMARKET LLC",
      "FOOD CENTER SUPERMARKET LLC"
    ],
    Tuesday: [
      "WORLD DISCOUNT MARKET",
      "EMIRATES GALLERY",
      "TOP 20",
      "AL KHALEEJ MARKET",
      "DAY TO DAY TRADING",
      "VALUE BAG",
      "METRO MANILA SM"
    ],
    Wednesday: [
      "20 PLAZA",
      "EMIRATES GALLERY",
      "TOP 10",
      "ALI BABA DISCOUNT MARKET",
      "SAMA AL KHALEEJ",
      "EMIRATES GALLERY DISCOUNT",
      "EVERY DAY CENTER"
    ],
    Thursday: [
      "PALM DISCOUNT CENTER",
      "JOINT TR",
      "BIDIYA SM",
      "CAPITAL SM",
      "JOINT TR",
      "JOINT TR"
    ],
    Friday: [
      "ALI BABA DISCOUNT",
      "ALI BABA DISCOUNT",
      "AL KHALEEJ MARKET",
      "EMIRATES DISCOUNT MARKET",
      "SUN AND SAND DISCOUNT"
    ],
    Saturday: [
      "CITY MARKET",
      "EMIRATES GALLERY DISCOUNT",
      "METRO MANILA SM",
      "REEM HYPER",
      "ALI BABA DISCOUNT MARKET",
      "20 PLAZA"
    ]
  },

  "Week 4": {
    Monday: [
      "SEVEN PLUS SUPERMARKET CO LLC",
      "FRESH MORE MINI MART LLC",
      "CARRY FOOD MINI MART LLC",
      "PLUS POINT MINI MART",
      "FRESH CARE MINI MART",
      "MARINA KP MART LLC",
      "MARINA SUITS SUPERMARKET LLC",
      "SPEEDWAY MARKET SUPERMARKET LLC",
      "SPEEDWAY MARKET SUPERMARKET LLC",
      "BUY MORE SUPERMARKET LLC",
      "CARRY FOOD SUPERMARKET LLC",
      "CARRY FOOD SUPERMARKET LLC"
    ],
    Tuesday: [
      "ONLINE GRO MEDIA CITY",
      "FRESH WAY MINI MART",
      "STRIPES SM",
      "FULL BASKET SUPERMARKET LLC",
      "J A I MINIMART FZ LLC",
      "FRESH WAY MINI MART LLC",
      "K P MART MINI MART LLC",
      "FULL STAR SUPERMARKET LLC",
      "CENTURY HARVEST SUPERMARKET LLC",
      "SUFOUH GARDENS SUPERMARKET LLC",
      "THE WOODEN SPOON RESTAURANT LLC",
      "SELLA MINI MART FZ LLC",
      "SHANDIZ PALACE RESTAURANT EST"
    ],
    Wednesday: [
      "FULL CART MINI MART LLC",
      "STAR MART SUPERMARKET LLC",
      "RENEE SUPERMARKET LLC",
      "RENEE SUPERMARKET LLC",
      "BEST BUY SUPERMARKET LLC",
      "SEVEN MARKET LLC",
      "BEST HOME MARKET LLC",
      "ALL SEASON MINI MART LLC",
      "BERRIES MINI MART LLC",
      "ATLANTICS SUPERMARKET LLC",
      "DAY PICK MINI MART LLC",
      "BEST IN VILLAGE SUPERMARKET LLC",
      "ZAYTUN SAHARA MINI MART LLC",
      "PALM TREE MINI MART",
      "SHOPRITE MINI MART FZCO"
    ],
    Thursday: [
      "LOYAL MINI MART LLC",
      "CARRYFOOD FRESH MINI MART LLC",
      "HEARTLAND SUPERMARKET LLC",
      "OMRAN ALJASMI GROCERY LLC",
      "ASAS AL MADINA SUPERMARKET LLC",
      "BIGBUY EXPRESS SUPERMARKET LLC",
      "AL TANAFUS GROCERY STORE LLC",
      "LOFT MINI MART LLC"
    ],
    Friday: [
      "BLUE MART FRESH MINI MART LLC",
      "BLUE MART FRESH MINI MART LLC"
    ],
    Saturday: [
      "FULL CART SUPERMARKET LLC",
      "CARRY FOOD PLUS MINI MART LLC",
      "FULL CART MINI MART LLC",
      "FRESH BASKET SUPERMARKET LLC",
      "FOR LEO GOURMET MINI MART LLC",
      "ALBASHAYER MINI MART LLC"
    ]
  }
  }
  
}

const WEEKS = ["Week 1", "Week 2", "Week 3", "Week 4"]
const DAYS  = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
// ── END OF FILL IN SECTION ─────────────────────────────────────


function App() {

  const [selectedSalesman, setSelectedSalesman] = useState("")
  const [selectedWeek, setSelectedWeek]         = useState("")
  const [selectedDay, setSelectedDay]           = useState("")
  const [selectedStore, setSelectedStore]       = useState("")
  const [selectedBrand, setSelectedBrand]       = useState("")
  const [products, setProducts]                 = useState({})
  const [toast, setToast]                       = useState(false)
  const [loading, setLoading]                   = useState(false)


  function handleProductToggle(skuName) {
    setProducts({
      ...products,
      [skuName]: !products[skuName]
    })
  }


  // now looks up stores using salesman + week + day
  function getStoresForDay() {
    if (!selectedSalesman || !selectedWeek || !selectedDay) return []
    return SCHEDULE[selectedSalesman]?.[selectedWeek]?.[selectedDay] || []
  }


  function handleSalesmanChange(name) {
    setSelectedSalesman(name)
    setSelectedWeek("")
    setSelectedDay("")
    setSelectedStore("")
    setSelectedBrand("")
    setProducts({})
  }


  function handleWeekChange(week) {
    setSelectedWeek(week)
    setSelectedDay("")
    setSelectedStore("")
    setSelectedBrand("")
    setProducts({})
  }


  function handleDayChange(day) {
    setSelectedDay(day)
    setSelectedStore("")
    setSelectedBrand("")
    setProducts({})
  }


  function handleStoreChange(store) {
    setSelectedStore(store)
    setSelectedBrand("")
    setProducts({})
  }


  async function handleSubmit() {
    setLoading(true)
  
    const today = new Date().toLocaleDateString("en-GB")
  
    // build one object where each brand name is a key
    // and its value is a comma separated string of checked SKUs
    const brandColumns = {}
    Object.entries(PRODUCTS).forEach(([brand, skus]) => {
      const checkedSkus = skus.filter((sku) => !!products[sku])
      // if nothing checked for this brand, save empty string
      brandColumns[brand] = checkedSkus.join(", ")
    })
  
    // the final row looks like:
    // { salesman: "Ahmed", week: "Week 1", day: "Monday", date: "18/04/2026",
    //   store: "Store 1", "Brand 1": "SKU 1A, SKU 1C", "Brand 2": "", "Brand 3": "SKU 3B" }
    const row = {
      salesman: selectedSalesman,
      week:     selectedWeek,
      day:      selectedDay,
      date:     today,
      store:    selectedStore,
      ...brandColumns,  // spreads all brand columns into the row
    }
  
    const { error } = await supabase.from("submissions").insert([row])
  
    setLoading(false)
  
    if (error) {
      alert("Something went wrong: " + error.message)
      return
    }
  
    setToast(true)
    setTimeout(() => setToast(false), 3000)
    setSelectedStore("")
    setSelectedBrand("")
    setProducts({})
  }


  const availableStores = getStoresForDay()
  const brandNames      = Object.keys(PRODUCTS)


  return (
    <>
      {/* ── HEADER ── */}
      <header className="header">
        <img src={logo} alt="Baqer Mohebi Enterprises" />
        <div className="header-divider" />
        <span className="header-title">Store Tracker</span>
      </header>

      <main className="page">

        {/* ── STEP 1: SALESMAN ── */}
        <div className="card">
          <div className="step-label">Step 1 — Who are you?</div>
          <label>Select your name</label>
          <select
            value={selectedSalesman}
            onChange={(e) => handleSalesmanChange(e.target.value)}
          >
            <option value="">— Select name —</option>
            {SALESMEN.map((name) => (
              <option key={name} value={name}>{name}</option>
            ))}
          </select>
        </div>


        {/* ── STEP 2: WEEK ── */}
        {selectedSalesman && (
          <div className="card">
            <div className="step-label">Step 2 — Which week?</div>
            <label>Select week</label>
            <select
              value={selectedWeek}
              onChange={(e) => handleWeekChange(e.target.value)}
            >
              <option value="">— Select week —</option>
              {WEEKS.map((week) => (
                <option key={week} value={week}>{week}</option>
              ))}
            </select>
          </div>
        )}


        {/* ── STEP 3: DAY ── */}
        {selectedWeek && (
          <div className="card">
            <div className="step-label">Step 3 — What day is it?</div>
            <label>Select day</label>
            <select
              value={selectedDay}
              onChange={(e) => handleDayChange(e.target.value)}
            >
              <option value="">— Select day —</option>
              {DAYS.map((day) => (
                <option key={day} value={day}>{day}</option>
              ))}
            </select>
          </div>
        )}


        {/* ── STEP 4: STORE ── */}
        {selectedDay && availableStores.length > 0 && (
          <div className="card">
            <div className="step-label">Step 4 — Which store?</div>
            <label>Select store</label>
            <select
              value={selectedStore}
              onChange={(e) => handleStoreChange(e.target.value)}
            >
              <option value="">— Select store —</option>
              {availableStores.map((store) => (
                <option key={store} value={store}>{store}</option>
              ))}
            </select>
          </div>
        )}

        {/* no stores assigned */}
        {selectedDay && availableStores.length === 0 && (
          <div className="card">
            <p className="no-stores">No stores assigned for this day.</p>
          </div>
        )}


        {/* ── STEP 5: BRANDS + SKUs ── */}
        {selectedStore && (
          <div className="card">
            <div className="step-label">Step 5 — Products</div>

            {/* brand pill tabs */}
            <div className="brand-tabs">
              {brandNames.map((brand) => {
                const checkedInBrand = PRODUCTS[brand].filter(sku => !!products[sku]).length
                const isActive       = selectedBrand === brand
                const hasChecks      = checkedInBrand > 0

                return (
                  <button
                    key={brand}
                    className={`brand-tab ${isActive ? "active" : ""} ${hasChecks ? "has-checks" : ""}`}
                    onClick={() => setSelectedBrand(brand)}
                  >
                    {brand}
                    {hasChecks && (
                      <span className="brand-tab-badge">{checkedInBrand}</span>
                    )}
                  </button>
                )
              })}
            </div>

            {/* SKUs for selected brand */}
            {selectedBrand && (
              <>
                <div className="products-header">
                  <span className="products-title">{selectedBrand}</span>
                  <span className="products-count">
                    {PRODUCTS[selectedBrand].filter(sku => !!products[sku]).length} / {PRODUCTS[selectedBrand].length} checked
                  </span>
                </div>

                <div className="products-grid">
                  {PRODUCTS[selectedBrand].map((sku) => (
                    <label
                      key={sku}
                      className={`product-item ${products[sku] ? "checked" : ""}`}
                    >
                      <input
                        type="checkbox"
                        checked={!!products[sku]}
                        onChange={() => handleProductToggle(sku)}
                      />
                      <div className="custom-check">
                        <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
                          <path d="M1 4L3.5 6.5L9 1" stroke="white" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                      </div>
                      <span className="product-name">{sku}</span>
                    </label>
                  ))}
                </div>
              </>
            )}

            <button
              className="submit-btn"
              onClick={handleSubmit}
              disabled={loading}
            >
              {loading ? "Submitting..." : "Submit"}
            </button>

          </div>
        )}

      </main>

      {/* ── SUCCESS TOAST ── */}
      {toast && (
        <div className="toast">✓ Submitted successfully</div>
      )}
    </>
  )
}

export default App